config/routes.rb
Rails.application.routes.draw do

  resources :students
  resources :tracks
  
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'registration/new'
  get 'registration/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'register', to: 'registration#new'
  post 'register', to: 'registration#create'

  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :track

  validates :name, presence: true
  validates :age, numericality: { only_integer: true, greater_than: 0 }
  validates :track_id, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
    has_many :students
  
    validates :name, presence: true, uniqueness: true
  end
  

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:error] = 'You must be logged in to access this page.'
      redirect_to login_path
    end
  end

  def logged_in?
    session[:user_id].present?
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: 'Registration successful. Please log in.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      flash.now[:alert] = 'Invalid email or password.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :set_student, only: [:show, :edit, :update, :destroy]
  
    def index
      @students = Student.all
    end
  
    def show
    end
  
    def new
      @student = Student.new
    end
  
    def create
      @student = Student.new(student_params)
  
      if @student.save
        redirect_to @student, notice: 'Student was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @student.update(student_params)
        redirect_to @student, notice: 'Student was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @student.destroy
      redirect_to students_url, notice: 'Student was successfully destroyed.'
    end
  
    private
  
    def set_student
      @student = Student.find(params[:id])
    end
  
    def student_params
      params.require(:student).permit(:name, :age, :track_id)
    end
  end
  

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    before_action :set_track, only: [:show, :edit, :update, :destroy]
  
    def index
      @tracks = Track.all
    end
  
    def show
    end
  
    def new
      @track = Track.new
    end
  
    def create
      @track = Track.new(track_params)
  
      if @track.save
        redirect_to @track, notice: 'Track was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @track.update(track_params)
        redirect_to @track, notice: 'Track was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @track.destroy
      redirect_to tracks_url, notice: 'Track was successfully destroyed.'
    end
  
    private
  
    def set_track
      @track = Track.find(params[:id])
    end
  
    def track_params
      params.require(:track).permit(:name, :description)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h1>Login</h1>
<%= form_with(url: session_path) do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit 'Login' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>
<%= form_with(model: @student, url: student_path(@student), method: :patch) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>
  <div>
    <%= form.label :track_id %>
    <%= form.collection_select :track_id, Track.all, :id, :name %>
  </div>
  <div>
    <%= form.submit 'Update Student' %>
  </div>
<% end %>
<br>
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>All Students</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Track</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.track.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>
<%= form_with(model: @student, url: students_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% if @student.errors.has_key?(:name) %>
      <div class="error">
        <%= @student.errors[:name].first %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
    <% if @student.errors.has_key?(:age) %>
      <div class="error">
        <%= @student.errors[:age].first %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :track_id %>
    <%= form.collection_select :track_id, Track.all, :id, :name %>
    <% if @student.errors.has_key?(:track_id) %>
      <div class="error">
        <%= @student.errors[:track_id].first %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit 'Create Student' %>
  </div>
<% end %>
<br>
<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<h1>Student Details</h1>
<p><strong>Name:</strong> <%= @student.name %></p>
<p><strong>Age:</strong> <%= @student.age %></p>
<p><strong>Track:</strong> <%= @student.track.name %></p>
<br>
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>
<%= form_with(model: @track, url: track_path(@track), method: :patch) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit 'Update Track' %>
  </div>
<% end %>
<br>
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>All Tracks</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.name %></td>
        <td><%= track.description %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>
<%= form_with(model: @track, url: tracks_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% if @track.errors.has_key?(:name) %>
      <div class="error">
        <%= @track.errors[:name].first %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <% if @track.errors.has_key?(:description) %>
      <div class="error">
        <%= @track.errors[:description].first %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit 'Create Track' %>
  </div>
<% end %>
<br>
<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<h1>Track Details</h1>
<p><strong>Name:</strong> <%= @track.name %></p>
<p><strong>Description:</strong> <%= @track.description %></p>
<br>
<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>